include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false

analyzer:
  error:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
