name: todo_riverpod_asyncvalue
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  flutter_spinkit: ^5.2.1
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  loader_overlay: ^4.0.0
  loading_overlay: ^0.3.0
  recase: ^4.1.0
  riverpod_annotation: ^2.3.0
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.8.0
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
